[package]
name = "Blinky_HAL"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
panic-halt = "1.0.0"

[dependencies.stm32f3]
version = "0.15.1"
features = ["stm32f303"]
