[package]
name = "Blinky"
version = "0.1.0"
edition = "2021"
include = ["memory.x", "src/**", "Cargo.toml", "Cargo.lock"]


[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
panic-halt = "1.0.0"

